### ISSUE TITLE
White screen add user

### ISSUE THREAD

**Issue by angelorocha** [bitcero/rmcommon#29]
Error adding new user.
Fatal error: Call to a member function name() on a non-object in
/modules/rmcommon/templates/rmc-users.php on line 239

See screen: http://goo.gl/IfCXhB

**Comment by bitcero** [comment]
Hi angelo... I can't reproduce this error... can you provide me more details?

**Comment by angelorocha** [comment]
Try add a user: /xfire/modules/rmcommon/users.php

**Comment by bitcero** [comment]
I've tried but I can't see any error...

**Comment by angelorocha** [comment]
Must complete the process of adding a user.

**Comment by bitcero** [comment]
Well... I've created a user selecting a specific group and all is ok. The problem comes when, in the user adding form you select the option "All". By selecting this option and save data, the problem occurs. I'll fix this now!
![select-group](https://cloud.githubusercontent.com/assets/1305172/9967997/a286d84e-5e0b-11e5-8b6a-3355e1849010.png)
