### ISSUE TITLE
How to set a native language?

### ISSUE THREAD

**Issue by panwac** [bitcero/rmcommon#52]
Hi,
I'm testing a Common Utilities + adforms +qpages on my test site now. After creating the files for my language (pl; polish) and sending them to directories in all modules I tryed to change the language in options 9Common Utilities), but i still have only 2 options: en and es. Could you help me to change it?

Piotr

**Comment by bitcero** [comment]
What is the procedure that you are following to create language files? Remember that you need to create a `.mo` file since yout `.po` file. You can use [Poedit](https://poedit.net/) to do that.

**Comment by panwac** [comment]
Mhmm - that was, why I wrote my question here. I saw, that the lang files system in your modules is different, than in xoops.

From the other site, only es lang has created .mo files in rmcommon, qpages and others - en has only .po. What is the reason?

Thanks for your answer

Peter

**Comment by panwac** [comment]
OK - problem solved. I'm creating polish lang now. :)

**Comment by bitcero** [comment]
Excelente! To respond your previous question: `en.po` is the base file to use when translate to other languages. `mo` file for `en` is not provided because the module has been created using English as base language. 

Remember, would be a very good appor if you can share your translations with other users. You can use **[Transifex][https://www.transifex.com/bitcero/rmcommon-modules/content/]** to do that.

**Comment by panwac** [comment]
Thanks for info.
I know transifex - a months ago it was used by me (great part of polish translation of xoops was made by me).
